# frozen_string_literal: true

require "json"
require "time"
require "date"

require_relative "database"

module VCTools
  module Podcast
    class DigestBuilder

      CROSSLINK_SECTORS = ["AI", "DevTools", "Infra", "Marketplace", "Consumer", "Vertical SaaS", "Health Tech"].freeze

      def initialize
        @db        = VCTools::Podcast::Database.connect
        @episodes  = @db[:episodes]
        @podcasts  = @db[:podcasts]
        @analyses  = @db[:episode_analyses]
        @digests   = @db[:daily_digests]
      end

      def run(date: Date.today)
        puts "[Digest] Building digest for #{date}"

        analyzed = fetch_analyzed_episodes(date)
        if analyzed.empty?
          puts "[Digest] No analyzed episodes for #{date}"
          return nil
        end

        markdown = build_markdown(date, analyzed)
        store_digest(date, markdown, analyzed.length)
        send_email(date, markdown)

        puts "[Digest] Done — #{analyzed.length} episodes, email sent"
        markdown
      end

      private

      def fetch_analyzed_episodes(date)
        # Get episodes analyzed in the last 24h (or all analyzed if running first time)
        cutoff = Time.new(date.year, date.month, date.day, 0, 0, 0).utc - 86400

        analyzed_ids = @episodes
          .where(status: "analyzed")
          .where { updated_at >= cutoff }
          .select_map(:id)

        return [] if analyzed_ids.empty?

        analyzed_ids.map do |ep_id|
          episode  = @episodes.where(id: ep_id).first
          podcast  = @podcasts.where(id: episode[:podcast_id]).first
          analysis = @analyses.where(episode_id: ep_id).first
          next unless analysis

          {
            podcast_name:       podcast[:name],
            title:              episode[:title],
            published_at:       episode[:published_at],
            summary:            analysis[:summary_md],
            key_takeaways:      JSON.parse(analysis[:key_takeaways_json] || "[]"),
            investment_signals: JSON.parse(analysis[:investment_signals_json] || "[]"),
            risks:              JSON.parse(analysis[:risks_json] || "[]"),
            action_items:       JSON.parse(analysis[:action_items_json] || "[]")
          }
        end.compact.then { |eps| select_diverse(eps) }
      end

      # Select 3 episodes for the digest, one per podcast (diversity first)
      def select_diverse(episodes, count: 3)
        episodes
          .group_by { |ep| ep[:podcast_name] }
          .flat_map { |_name, eps| eps.first(1) }
          .sort_by  { |ep| ep[:published_at] }
          .last(count)
      end

      def build_markdown(date, analyzed)
        lines = []

        # Header
        lines << "# VC Podcast Digest — #{date}"
        lines << ""
        lines << "**#{analyzed.length} episodes** | Generated #{Time.now.utc.strftime('%Y-%m-%d %H:%M UTC')}"
        lines << ""
        lines << "---"
        lines << ""

        # Full writeup for each episode
        analyzed.each_with_index do |ep, i|
          lines << "## #{i + 1}. #{ep[:podcast_name]}: #{ep[:title]}"
          lines << ""

          # The summary_md field now contains the full 500-1000 word analysis
          lines << ep[:summary] if ep[:summary]
          lines << ""
          lines << "---"
          lines << ""
        end

        # Footer
        lines << "_Crosslink Focus: #{CROSSLINK_SECTORS.join(' | ')}_"
        lines << ""
        lines << "_Generated by Marcello's VC Signal Tools_"

        lines.join("\n")
      end

      def store_digest(date, markdown, episode_count)
        existing = @digests.where(digest_date: date).first
        if existing
          @digests.where(id: existing[:id]).update(
            content_md:      markdown,
            episode_count:   episode_count,
            delivery_status: "pending"
          )
        else
          @digests.insert(
            digest_date:     date,
            content_md:      markdown,
            episode_count:   episode_count,
            delivery_status: "pending"
          )
        end
      end

      def send_email(date, markdown)
        require "mail"
        require "dotenv/load"

        return puts "[Digest] No SMTP config, skipping email" unless ENV["SMTP_USERNAME"]

        Mail.defaults do
          delivery_method :smtp, {
            address:              ENV["SMTP_ADDRESS"] || "smtp.gmail.com",
            port:                 ENV.fetch("SMTP_PORT", 587).to_i,
            user_name:            ENV["SMTP_USERNAME"],
            password:             ENV["SMTP_PASSWORD"],
            authentication:       :plain,
            enable_starttls_auto: true,
            open_timeout:         15,
            read_timeout:         15
          }
        end

        to_addr = ENV.fetch("ALERT_TO_EMAIL", ENV["SMTP_USERNAME"])
        body    = markdown

        Mail.deliver do
          from    ENV.fetch("SMTP_FROM", ENV["SMTP_USERNAME"])
          to      to_addr
          subject "VC Podcast Digest — #{date}"
          body    body
        end

        @digests.where(digest_date: date).update(
          sent_at:         Time.now.utc,
          delivery_status: "sent"
        )

      rescue => e
        puts "[Digest] Email error: #{e.message}"
        @digests.where(digest_date: date).update(delivery_status: "failed")
      end

    end
  end
end
