# frozen_string_literal: true

require "json"
require "time"
require "date"

require_relative "database"

module VCTools
  module Podcast
    class DigestBuilder

      CROSSLINK_SECTORS = ["AI", "DevTools", "Infra", "Marketplace", "Consumer", "Vertical SaaS", "Health Tech"].freeze

      def initialize
        @db        = VCTools::Podcast::Database.connect
        @episodes  = @db[:episodes]
        @podcasts  = @db[:podcasts]
        @analyses  = @db[:episode_analyses]
        @digests   = @db[:daily_digests]
      end

      def run(date: Date.today)
        puts "[Digest] Building digest for #{date}"

        analyzed = fetch_analyzed_episodes(date)
        if analyzed.empty?
          puts "[Digest] No analyzed episodes for #{date}"
          return nil
        end

        markdown = build_markdown(date, analyzed)
        store_digest(date, markdown, analyzed.length)
        send_email(date, markdown)

        puts "[Digest] Done — #{analyzed.length} episodes, email sent"
        markdown
      end

      private

      def fetch_analyzed_episodes(date)
        # Get episodes analyzed in the last 24h (or all analyzed if running first time)
        cutoff = Time.new(date.year, date.month, date.day, 0, 0, 0).utc - 86400

        analyzed_ids = @episodes
          .where(status: "analyzed")
          .where { updated_at >= cutoff }
          .select_map(:id)

        return [] if analyzed_ids.empty?

        analyzed_ids.map do |ep_id|
          episode  = @episodes.where(id: ep_id).first
          podcast  = @podcasts.where(id: episode[:podcast_id]).first
          analysis = @analyses.where(episode_id: ep_id).first
          next unless analysis

          {
            podcast_name:       podcast[:name],
            title:              episode[:title],
            published_at:       episode[:published_at],
            summary:            analysis[:summary_md],
            key_takeaways:      JSON.parse(analysis[:key_takeaways_json] || "[]"),
            investment_signals: JSON.parse(analysis[:investment_signals_json] || "[]"),
            risks:              JSON.parse(analysis[:risks_json] || "[]"),
            action_items:       JSON.parse(analysis[:action_items_json] || "[]")
          }
        end.compact.then { |eps| select_diverse(eps) }
      end

      # Select 3 episodes for the digest, one per podcast (diversity first)
      def select_diverse(episodes, count: 3)
        episodes
          .group_by { |ep| ep[:podcast_name] }
          .flat_map { |_name, eps| eps.first(1) }
          .sort_by  { |ep| ep[:published_at] }
          .last(count)
      end

      def build_markdown(date, analyzed)
        lines = []

        # Header
        lines << "# VC Podcast Digest — #{date}"
        lines << ""
        lines << "**#{analyzed.length} episodes** | Generated #{Time.now.utc.strftime('%Y-%m-%d %H:%M UTC')}"
        lines << ""
        lines << "---"
        lines << ""

        # Full writeup for each episode
        analyzed.each_with_index do |ep, i|
          lines << "## #{i + 1}. #{ep[:podcast_name]}: #{ep[:title]}"
          lines << ""

          # The summary_md field contains the full 500-1000 word analysis
          # Strip any "Bottom Line" conclusion the LLM may have added
          summary = ep[:summary] || ""
          summary = summary.sub(/\n*###?\s*Bottom Line.*\z/mi, "").rstrip
          lines << summary unless summary.empty?
          lines << ""

          if !ep[:key_takeaways].empty? || !ep[:investment_signals].empty?
            lines << "#### Key Takeaways and Investment Signals"
            ep[:key_takeaways].first(5).each { |t| lines << "- #{t}" }
            ep[:investment_signals].each do |sig|
              sig = sig.is_a?(Hash) ? sig : JSON.parse(sig) rescue next
              lines << "- **[#{sig['sector']}]** #{sig['signal']} — #{sig['why_it_matters']}"
            end
            lines << ""
          end

          lines << "---"
          lines << ""
        end

        # Footer
        lines << "_Crosslink Focus: #{CROSSLINK_SECTORS.join(' | ')}_"
        lines << ""
        lines << "_Generated by Marcello's VC Signal Tools_"

        lines.join("\n")
      end

      def store_digest(date, markdown, episode_count)
        existing = @digests.where(digest_date: date).first
        if existing
          @digests.where(id: existing[:id]).update(
            content_md:      markdown,
            episode_count:   episode_count,
            delivery_status: "pending"
          )
        else
          @digests.insert(
            digest_date:     date,
            content_md:      markdown,
            episode_count:   episode_count,
            delivery_status: "pending"
          )
        end
      end

      def send_email(date, markdown)
        require "resend"
        require "dotenv/load"

        return puts "[Digest] No RESEND_API_KEY, skipping email" unless ENV["RESEND_API_KEY"]

        Resend.api_key = ENV["RESEND_API_KEY"]

        recipients = ENV.fetch("ALERT_TO_EMAIL", "marcellobattista@outlook.com")
                       .split(",").map(&:strip)

        html = markdown_to_html(markdown)

        Resend::Emails.send({
          from:    "VC Signal Tools <onboarding@resend.dev>",
          to:      recipients,
          subject: "VC/Tech Podcast Digest - #{date}",
          html:    html
        })

        @digests.where(digest_date: date).update(
          sent_at:         Time.now.utc,
          delivery_status: "sent"
        )

      rescue => e
        puts "[Digest] Email error: #{e.message}"
        @digests.where(digest_date: date).update(delivery_status: "failed")
      end

      def markdown_to_html(md)
        lines = md.lines.map(&:rstrip)
        html_lines = lines.map do |line|
          case line
          when /^#### (.+)/  then "<h4>#{$1}</h4>"
          when /^### (.+)/   then "<h3>#{$1}</h3>"
          when /^## (.+)/    then "<h2>#{$1}</h2>"
          when /^# (.+)/     then "<h1>#{$1}</h1>"
          when /^---$/       then "<hr>"
          when /^- (.+)/     then "<li>#{$1}</li>"
          when /^\s*$/       then ""
          else                    "<p>#{line}</p>"
          end
        end

        # Wrap consecutive <li> items in <ul>
        result = html_lines.join("\n")
          .gsub(/(<li>.*?<\/li>\n?)+/) { |m| "<ul>\n#{m}</ul>\n" }

        # Inline formatting: **bold** and _italic_
        result.gsub!(/\*\*(.+?)\*\*/, '<strong>\1</strong>')
        result.gsub!(/(?<!\w)_(.+?)_(?!\w)/, '<em>\1</em>')

        "<div style=\"font-family: -apple-system, Arial, sans-serif; max-width: 700px; margin: 0 auto; line-height: 1.6;\">#{result}</div>"
      end

    end
  end
end
